from forms.form_classes import FormVar, FormConst

# Variables are lowercase
a = FormVar('a')
b = FormVar('b')
c = FormVar('c')
d = FormVar('d')
# e = FormVar('e')
f = FormVar('f')
g = FormVar('g')
h = FormVar('h')
i = FormVar('i')
j = FormVar('j')
k = FormVar('k')
l = FormVar('l')
m = FormVar('m')
n = FormVar('n')
o = FormVar('o')
p = FormVar('p')
q = FormVar('q')
r = FormVar('r')
s = FormVar('s')
t = FormVar('t')
u = FormVar('u')
v = FormVar('v')
w = FormVar('w')
x = FormVar('x')
y = FormVar('y')
z = FormVar('z')

# Constants are uppercase
A = FormConst('A')
B = FormConst('B')
C = FormConst('C')
D = FormConst('D')
E = FormConst('E')
F = FormConst('F')
G = FormConst('G')
H = FormConst('H')
I = FormConst('I')
J = FormConst('J')
K = FormConst('K')
L = FormConst('L')
M = FormConst('M')
N = FormConst('N')
O = FormConst('O')
P = FormConst('P')
Q = FormConst('Q')
R = FormConst('R')
S = FormConst('S')
T = FormConst('T')
U = FormConst('U')
V = FormConst('V')
W = FormConst('W')
X = FormConst('X')
Y = FormConst('Y')
Z = FormConst('Z')