from forms.form_classes import FormVar, FormConst

# Variables are lowercase
a = FormVar('a')
b = FormVar('b')
c = FormVar('c')
d = FormVar('d')
e = FormVar('e')
f = FormVar('f')
g = FormVar('g')
h = FormVar('h')
i = FormVar('i')
j = FormVar('j')
k = FormVar('k')
l = FormVar('l')
m = FormVar('m')
n = FormVar('n')
o = FormVar('o')
p = FormVar('p')
q = FormVar('q')
r = FormVar('r')
s = FormVar('s')
t = FormVar('t')
u = FormVar('u')
v = FormVar('v')
w = FormVar('w')
x = FormVar('x')
y = FormVar('y')
z = FormVar('z')

# Constants are uppercase
A = FormConst('a')
B = FormConst('b')
C = FormConst('c')
D = FormConst('d')
E = FormConst('e')
F = FormConst('f')
G = FormConst('g')
H = FormConst('h')
I = FormConst('i')
J = FormConst('j')
K = FormConst('k')
L = FormConst('l')
M = FormConst('m')
N = FormConst('n')
O = FormConst('o')
P = FormConst('p')
Q = FormConst('q')
R = FormConst('r')
S = FormConst('s')
T = FormConst('t')
U = FormConst('u')
V = FormConst('v')
W = FormConst('w')
X = FormConst('x')
Y = FormConst('y')
Z = FormConst('z')